### ISSUE TITLE
Crash on picking up a single, standing Aether water source block with an iron bucket

### ISSUE THREAD

**Issue by Blink18260000** [gildedgames/aether-issues#395]
Given a single, standing water source block that's flowing down a hill, on trying to pick it up with an iron bucket, the game crashes. 

0 is an empty block, W is a source block, and f is flowing water.

0 0 0
0 W f
0 0 0

I have confirmed this is the source of the issue by replicating the problem in a test world. 

Copied below is the error report that is generated:

---- Minecraft Crash Report ----
// Sorry :(

Time: 2/17/15 4:33 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_147460_e(World.java:714)
	at net.minecraft.world.World.func_147459_d(World.java:652)
	at net.minecraft.world.World.func_147444_c(World.java:613)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:488)
	at net.minecraft.world.World.func_147465_d(World.java:466)
	at net.minecraft.world.World.func_147468_f(World.java:573)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:86)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.7.0_67, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 216303136 bytes (206 MB) / 518656000 bytes (494 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 6 mods loaded, 6 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	gilded-games-util{1.7.10-1.0} [Gilded Games Utility] (gilded-games-util-1.7.10-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	aether{Alpha 1.7.10-1.0} [Aether II] (aether.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Blink18260000'/225, l='Test World', x=-323.06, y=78.00, z=-116.74]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Collin1971** [comment]
I cannot reproduce this issue with the following configuration you described:

![gSAeBBB.png](http://i.imgur.com/gSAeBBB.png)

**Comment by Collin1971** [comment]
I believe the issue might've been caused by #436 because somewhere in the Aether code during world generation we set block ticks to be instant, probably causing a few issues with water. (because water pretty much completely works with the idea of ticks)

**Comment by PGMacDesign** [comment]
This seems to still be happening. If I place water ANYWHERE in the overworld via a bucket. It crashes the entire server via an exception. 
Here is the full printout:
[03:05:08] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.FillBucketEvent@17a356e:
java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
        at net.aetherteam.aether.AetherEvents.onFillBucket(AetherEvents.java:133) ~[AetherEvents.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_26_AetherEvents_onFillBucket_FillBucketEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:39) [abo.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146) [add.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316) [mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539) [nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[03:05:08] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[03:05:08] [Server thread/ERROR] [FML]: 0: NORMAL
[03:05:08] [Server thread/ERROR] [FML]: 1: ASM: net.aetherteam.aether.AetherEvents@2c1446 onFillBucket(Lnet/minecraftforge/event/entity/player/FillBucketEvent;)V
[03:05:08] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
        at net.aetherteam.aether.AetherEvents.onFillBucket(AetherEvents.java:133) ~[AetherEvents.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_26_AetherEvents_onFillBucket_FillBucketEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:39) ~[abo.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146) ~[add.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[03:05:08] [Server thread/ERROR]: This crash report has been saved to: C:\Users\jon\Documents\Minecraft\Minecraft Server - Aether II\.\crash-reports\crash-2015-11-09_03.05.08-server.txt
[03:05:08] [Server thread/INFO]: Stopping server
[03:05:08] [Server thread/INFO]: Saving players
[03:05:08] [Server thread/INFO]: Saving worlds
[03:05:08] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[03:05:09] [Server thread/INFO]: Saving chunks for level 'world'/Nether
[03:05:09] [Server thread/INFO]: Saving chunks for level 'world'/The End
[03:05:09] [Server thread/INFO]: Saving chunks for level 'world'/Dungeons
[03:05:09] [Server thread/INFO]: Saving chunks for level 'world'/Aether
[03:05:09] [Server thread/INFO] [FML]: Unloading dimension 0
[03:05:09] [Server thread/INFO] [FML]: Unloading dimension -1
[03:05:09] [Server thread/INFO] [FML]: Unloading dimension 1
[03:05:09] [Server thread/INFO] [FML]: Unloading dimension 4
[03:05:09] [Server thread/INFO] [FML]: Unloading dimension 3
[03:05:09] [Server thread/INFO] [FML]: Applying holder lookups
[03:05:09] [Server thread/INFO] [FML]: Holder lookups applied
[03:05:09] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded[03:04:49] [Server thread/INFO]: Silmarilos joined the game
[03:05:08] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.FillBucketEvent@17a356e:
java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
        at net.aetherteam.aether.AetherEvents.onFillBucket(AetherEvents.java:133) ~[AetherEvents.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_26_AetherEvents_onFillBucket_FillBucketEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:39) [abo.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146) [add.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316) [mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539) [nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) [jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) [jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[03:05:08] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[03:05:08] [Server thread/ERROR] [FML]: 0: NORMAL
[03:05:08] [Server thread/ERROR] [FML]: 1: ASM: net.aetherteam.aether.AetherEvents@2c1446 onFillBucket(Lnet/minecraftforge/event/entity/player/FillBucketEvent;)V
[03:05:08] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
        at net.aetherteam.aether.AetherEvents.onFillBucket(AetherEvents.java:133) ~[AetherEvents.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_26_AetherEvents_onFillBucket_FillBucketEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:39) ~[abo.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146) ~[add.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539) ~[nh.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[03:05:08] [Server thread/ERROR]: This crash report has been saved to: C:\Users\jon\Documents\Minecraft\Minecraft Server - Aether II\.\crash-reports\crash-2015-11-09_03.05.08-server.txt
[03:05:08] [Server thread/INFO]: Stopping server
[03:05:08] [Server thread/INFO]: Saving players
[03:05:08] [Server thread/INFO]: Saving worlds
[03:05:08] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[03:05:09] [Server thread/INFO]: Saving chunks for level 'world'/Nether
[03:05:09] [Server thread/INFO]: Saving chunks for level 'world'/The End
[03:05:09] [Server thread/INFO]: Saving chunks for level 'world'/Dungeons
[03:05:09] [Server thread/INFO]: Saving chunks for level 'world'/Aether
[03:05:09] [Server thread/INFO] [FML]: Unloading dimension 0
[03:05:09] [Server thread/INFO] [FML]: Unloading dimension -1
[03:05:09] [Server thread/INFO] [FML]: Unloading dimension 1
[03:05:09] [Server thread/INFO] [FML]: Unloading dimension 4
[03:05:09] [Server thread/INFO] [FML]: Unloading dimension 3
[03:05:09] [Server thread/INFO] [FML]: Applying holder lookups
[03:05:09] [Server thread/INFO] [FML]: Holder lookups applied
[03:05:09] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded..

**Comment by Collin1971** [comment]
@PGMacDesign Update Forge to 10.13.4.1448.

**Comment by PGMacDesign** [comment]
That solved the problem, ty for the help Collin!
